import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from '../worker/index.mjs';
const base='https://campusbridge.test';
const pdf=Buffer.from('%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF');
const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0,73,69,78,68,174,66,96,130]);
function setup(storage=true){
 const sqlite=new DatabaseSync(':memory:');for(const migration of readdirSync('migrations').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('migrations/'+migration,'utf8'));
 for(const [id,role] of [['student','student'],['other','student'],['recruiter','recruiter'],['outside','recruiter'],['admin','admin']]){sqlite.prepare('INSERT INTO users(id,name,email,password,salt,role) VALUES(?,?,?,?,?,?)').run(id,id,id+'@test.com','hash','salt',role);sqlite.prepare('INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)').run(id,id,Date.now()+60000);}
 const DB={prepare(sql){const stmt=sqlite.prepare(sql);const bind=(v=[])=>({first:async()=>stmt.get(...v)||null,all:async()=>({results:stmt.all(...v)}),run:async()=>({meta:stmt.run(...v)})});return {...bind(),bind:(...v)=>bind(v)};},async batch(queries){sqlite.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 const objects=new Map();const UPLOADS={async put(key,bytes,options){objects.set(key,{bytes:new Uint8Array(bytes),options});},async get(key){const o=objects.get(key);return o?{body:o.bytes,size:o.bytes.byteLength}:null;},async delete(key){objects.delete(key);}};
 const env={DB,AUTH_MODE:'demo',...(storage?{UPLOADS}:{}),ASSETS:{fetch:()=>new Response('asset')}};
 function call(path,user='student',options={}){const headers=new Headers(options.headers);if(user)headers.set('Cookie','cb_session='+user);return worker.fetch(new Request(base+path,{...options,headers}),env);}
 function upload(path='/api/resume',user='student',bytes=pdf,type='application/pdf',name='resume.pdf'){const form=new FormData();form.set('file',new File([bytes],name,{type}));return call(path,user,{method:'POST',body:form});}
 return {sqlite,DB,objects,env,call,upload,close:()=>sqlite.close()};
}
test('PDF upload persists a private immutable object and metadata without changing profile',async()=>{const s=setup();const r=await s.upload();assert.equal(r.status,200);const data=await r.json();assert.equal(data.type,'application/pdf');assert.equal(data.size,pdf.length);assert.match(data.url,/^https:\/\/campusbridge\.test\/api\/uploads\/[0-9a-f-]+$/);assert.equal(s.objects.size,1);assert.equal(s.sqlite.prepare('SELECT kind FROM uploads').get().kind,'resume');assert.equal(s.sqlite.prepare("SELECT resume FROM users WHERE id='student'").get().resume,'');s.close();});
test('uploads authenticate before reading multipart content',async()=>{const s=setup();const r=await s.call('/api/resume',null,{method:'POST',body:'not multipart'});assert.equal(r.status,401);assert.equal(s.objects.size,0);s.close();});
test('resume upload requires student role and configured storage',async()=>{const s=setup();assert.equal((await s.upload('/api/resume','recruiter')).status,403);s.close();const unavailable=setup(false);assert.equal((await unavailable.upload()).status,503);assert.equal((await (await unavailable.call('/api/auth/config',null)).json()).uploadsEnabled,false);unavailable.close();});
test('PDF validation rejects renamed HTML and wrong MIME',async()=>{const s=setup();assert.equal((await s.upload('/api/resume','student',Buffer.from('<html>bad</html>'))).status,400);assert.equal((await s.upload('/api/resume','student',pdf,'text/plain')).status,400);assert.equal(s.objects.size,0);s.close();});
test('PDF upload rejects files over 5MiB and untrusted mutation origins',async()=>{const s=setup();const large=Buffer.alloc(5*1024*1024+1);pdf.copy(large);assert.equal((await s.upload('/api/resume','student',large)).status,413);const form=new FormData();form.set('file',new File([pdf],'resume.pdf',{type:'application/pdf'}));assert.equal((await s.call('/api/resume','student',{method:'POST',headers:{Origin:'https://attacker.test'},body:form})).status,403);assert.equal(s.objects.size,0);s.close();});
test('avatar accepts PNG, stores upload source and rejects SVG masquerading as PNG',async()=>{const s=setup();const r=await s.upload('/api/avatar','recruiter',png,'image/png','photo.png');assert.equal(r.status,200);const data=await r.json();const user=s.sqlite.prepare("SELECT * FROM users WHERE id='recruiter'").get();assert.equal(user.avatar_url,data.url);assert.equal(user.avatar_source,'upload');assert.equal((await s.upload('/api/avatar','student',Buffer.from('<svg/>'),'image/png','fake.png')).status,400);assert.equal((await s.upload('/api/avatar','student',Buffer.alloc(2*1024*1024+1),'image/png','huge.png')).status,413);s.close();});
test('private file downloads allow owner/admin and deny other users',async()=>{const s=setup();const data=await (await s.upload()).json();const path=new URL(data.url).pathname;const r=await s.call(path);assert.equal(r.status,200);assert.deepEqual(Buffer.from(await r.arrayBuffer()),pdf);assert.equal(r.headers.get('Content-Type'),'application/pdf');assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.match(r.headers.get('Cache-Control'),/private/);assert.equal((await s.call(path,'other')).status,403);assert.equal((await s.call(path,'admin')).status,200);assert.equal((await s.call(path,null)).status,401);s.close();});
test('recruiter download access follows exact immutable application snapshot and owned company',async()=>{const s=setup();const first=await (await s.upload()).json();const second=await (await s.upload()).json();s.sqlite.prepare("INSERT INTO companies(id,owner_id,name,industry,status) VALUES('company','recruiter','Studio','Technology','approved')").run();s.sqlite.prepare("INSERT INTO jobs(id,company_id,title,type,location,salary,min_cgpa,departments,deadline,description,status) VALUES('job','company','Role','Full-time','Remote','100',0,'[]','2035-01-01','Role','approved')").run();s.sqlite.prepare("INSERT INTO applications(id,student_id,job_id,snapshot,history) VALUES('app','student','job',?,'[]')").run(JSON.stringify({resume:first.url}));assert.equal((await s.call(new URL(first.url).pathname,'recruiter')).status,200);assert.equal((await s.call(new URL(second.url).pathname,'recruiter')).status,403);assert.equal((await s.call(new URL(first.url).pathname,'outside')).status,403);assert.equal(s.objects.size,2);s.close();});
test('profile saving rejects another student managed resume and image references',async()=>{const s=setup();const resume=await (await s.upload('/api/resume','other')).json();const avatar=await (await s.upload('/api/avatar','student',png,'image/png','photo.png')).json();const body={name:'Student',department:'CSE',cgpa:8,graduation_year:2027,resume:resume.url};let r=await s.call('/api/profile','student',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,403);r=await s.call('/api/profile','student',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,resume:avatar.url})});assert.equal(r.status,400);s.close();});
test('metadata failure removes only the newly uploaded object',async()=>{const s=setup();s.sqlite.exec("CREATE TRIGGER refuse_upload BEFORE INSERT ON uploads BEGIN SELECT RAISE(ABORT,'database failure'); END;");assert.equal((await s.upload()).status,500);assert.equal(s.objects.size,0);assert.equal(s.sqlite.prepare('SELECT COUNT(*) AS n FROM uploads').get().n,0);s.close();});
test('actual multipart stream cap rejects oversized requests without a Content-Length',async()=>{const s=setup();let cancelled=false;const stream=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(6*1024*1024));},cancel(){cancelled=true;}});const r=await s.call('/api/resume','student',{method:'POST',headers:{'Content-Type':'multipart/form-data; boundary=test'},body:stream,duplex:'half'});assert.equal(r.status,413);assert.equal(cancelled,true);assert.equal(s.objects.size,0);s.close();});
test('avatar JPEG and WebP signatures are accepted and MIME-mismatched files rejected',async()=>{const s=setup();const jpeg=Buffer.from([255,216,255,224,0,0,255,217]),webp=Buffer.from('RIFF0000WEBPpayload');assert.equal((await s.upload('/api/avatar','admin',jpeg,'image/jpeg','photo.jpg')).status,200);assert.equal((await s.upload('/api/avatar','admin',webp,'image/webp','photo.webp')).status,200);assert.equal((await s.upload('/api/avatar','admin',jpeg,'image/png','photo.png')).status,400);s.close();});
test('recruiter can read snapshot avatar but cannot read newer replacement',async()=>{const s=setup();const first=await (await s.upload('/api/avatar','student',png,'image/png','first.png')).json();const second=await (await s.upload('/api/avatar','student',png,'image/png','second.png')).json();s.sqlite.prepare("INSERT INTO companies(id,owner_id,name,industry,status) VALUES('company','recruiter','Studio','Technology','approved')").run();s.sqlite.prepare("INSERT INTO jobs(id,company_id,title,type,location,salary,min_cgpa,departments,deadline,description,status) VALUES('job','company','Role','Full-time','Remote','100',0,'[]','2035-01-01','Role','approved')").run();s.sqlite.prepare("INSERT INTO applications(id,student_id,job_id,snapshot,history) VALUES('app','student','job',?,'[]')").run(JSON.stringify({avatar_url:first.url}));assert.equal((await s.call(new URL(first.url).pathname,'recruiter')).status,200);assert.equal((await s.call(new URL(second.url).pathname,'recruiter')).status,403);assert.equal(s.objects.size,2);s.close();});
