import {pbkdf2Sync} from 'node:crypto';
import {writeFileSync,mkdirSync} from 'node:fs';
const sql=[];const q=v=>v===null?'NULL':typeof v==='number'?String(v):"'"+String(v).replace(/'/g,"''")+"'";
const insert=(table,row)=>sql.push(`INSERT OR IGNORE INTO ${table} (${Object.keys(row).join(',')}) VALUES (${Object.values(row).map(q).join(',')});`);
const now=new Date();const at=days=>new Date(now.getTime()+days*86400000).toISOString().replace('T',' ').slice(0,19);const deadline=days=>at(days).slice(0,10);
const students=[['student-demo','Aarav Sharma','student@campusbridge.demo','CSE',8.6,'Frontend enthusiast, curious problem solver, and builder of thoughtful digital experiences. I love React, design systems, and making complex things feel simple.'],['student-low','Rohan Mehta','ineligible@campusbridge.demo','CSE',6.4,'Learning frontend development and building my first portfolio.'],['s2','Diya Patel','diya@campusbridge.demo','IT',9.1,'Full-stack engineer with a love for accessible interfaces and open source.'],['s3','Ishaan Rao','ishaan@campusbridge.demo','CSE',8.8,'Backend systems, distributed computing, and a healthy curiosity for how things work.'],['s4','Meera Iyer','meera@campusbridge.demo','ECE',8.3,'Product designer and electronics student interested in the intersection of people and technology.'],['s5','Arjun Nair','arjun@campusbridge.demo','IT',8.9,'I build practical tools using TypeScript and Python.'],['s6','Sana Khan','sana@campusbridge.demo','CSE',9.3,'Data science, machine learning, and asking better questions.'],['s7','Dev Shah','dev@campusbridge.demo','ME',8.1,'Mechanical engineering student passionate about sustainable design.']];
const profiles={};
for(const [id,name,email,department,cgpa,bio] of students){const salt='campusbridge-demo-'+id;const profile={id,name,email,department,cgpa,graduation_year:2027,resume:'https://example.com/resumes/'+id,bio};profiles[id]=profile;insert('users',{...profile,password:pbkdf2Sync('Campus@2026',salt,100000,32,'sha256').toString('hex'),salt,role:'student',created_at:at(-30)});}
const recruiters=[['recruiter-demo','Maya Kapoor','recruiter@campusbridge.demo'],['r2','Nikhil Verma','orbit@campusbridge.demo'],['r3','Priya Desai','northstar@campusbridge.demo'],['r4','Kavya Sen','monograph@campusbridge.demo'],['r5','Rishi Arora','forma@campusbridge.demo'],['r6','Ankit Roy','canopy@campusbridge.demo']];
for(const [id,name,email] of [...recruiters,['admin-demo','Ananya Rao','admin@campusbridge.demo']]){const salt='campusbridge-demo-'+id;insert('users',{id,name,email,password:pbkdf2Sync('Campus@2026',salt,100000,32,'sha256').toString('hex'),salt,role:id==='admin-demo'?'admin':'recruiter',created_at:at(-30)});}
const companies=[['c-layers','recruiter-demo','Layers','Product & Design','Bengaluru','≋','#e9dff7','approved','We build thoughtful digital products for people and teams. Our small, ambitious studio values curiosity, craft, and a fresh perspective. Help us turn complex challenges into experiences people love.'],['c-orbit','r2','Orbit','Developer Tools','Bengaluru','◉','#dfeace','approved','We are building the tools that help developers do their best work. Join a collaborative engineering team that values clean code, good questions, and continuous learning.'],['c-northstar','r3','Northstar','Technology & Data','Hyderabad','✦','#fae9c8','approved','We make data useful, accessible, and actionable. Our teams bring together analytical thinking and real-world impact to help businesses make better decisions.'],['c-monograph','r4','Monograph','Software & Collaboration','Pune','m.','#e8e6df','approved','We make the workday a little clearer. Build calm, focused software for creative teams and grow with an engineering culture that values thoughtful collaboration.'],['c-forma','r5','Forma','Engineering & Manufacturing','Mumbai','▰','#e6e4f3','pending','We are reimagining manufacturing with sustainable materials and precision engineering. We are looking for curious students to help shape the next generation of physical products.'],['c-canopy','r6','Canopy','Climate Technology','Chennai','♧','#dcebdc','pending','We help communities measure and reduce their environmental impact. Work with a growing climate technology team across data, design, and engineering.']];
for(const [id,owner_id,name,industry,location,logo,color,status,description] of companies)insert('companies',{id,owner_id,name,industry,location,logo,color,status,description,website:'https://example.com/companies/'+id,created_at:at(status==='pending'?-2:-22)});
const jobs=[['j-design','c-layers','Product Design Intern','Internship','Bengaluru','Hybrid','₹35,000',7.5,['CSE','IT','ECE'],['Figma','Design thinking','Prototyping'],20,'approved'],['j-frontend','c-orbit','Frontend Engineer','Full-time','Bengaluru','Hybrid','₹12–18 LPA',8,['CSE','IT'],['React','TypeScript','JavaScript'],25,'approved'],['j-data','c-northstar','Data Analyst Intern','Internship','Hyderabad','On-site','₹30,000',7.5,['CSE','IT','ECE'],['SQL','Python','Data visualization'],18,'approved'],['j-product','c-monograph','Associate Product Engineer','Full-time','Remote','Remote','₹10–14 LPA',8,['CSE','IT'],['Problem solving','React','Node.js'],30,'approved'],['j-fullstack','c-layers','Full Stack Developer','Full-time','Bengaluru','Hybrid','₹14–20 LPA',8.5,['CSE','IT'],['TypeScript','Node.js','PostgreSQL'],22,'approved'],['j-research','c-northstar','Machine Learning Intern','Internship','Hyderabad','Hybrid','₹45,000',9,['CSE','IT'],['Python','Machine learning','Statistics'],28,'approved'],['j-layers-new','c-layers','UI Engineering Intern','Internship','Bengaluru','Hybrid','₹40,000',7,['CSE','IT'],['CSS','React','Accessibility'],35,'pending'],['j-forma','c-forma','Graduate Design Engineer','Full-time','Mumbai','On-site','₹8–12 LPA',7,['ME','EEE'],['CAD','SolidWorks','Engineering design'],32,'pending'],['j-canopy','c-canopy','Software Engineering Intern','Internship','Chennai','Hybrid','₹25,000',7,['CSE','IT','ECE'],['JavaScript','Python','Git'],27,'pending']];
for(const [id,company_id,title,type,location,mode,salary,min_cgpa,depts,skills,days,status] of jobs)insert('jobs',{id,company_id,title,type,location,mode,salary,min_cgpa,departments:JSON.stringify(depts),skills:JSON.stringify(skills),deadline:deadline(days),status,description:`We’re looking for a curious, motivated ${title.toLowerCase()} to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.\nIn this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.\nBring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.`,created_at:at(status==='pending'?-2:-Math.floor(Number(days)/3))});
const applications=[['a-demo-design','student-demo','j-design','Shortlisted',-8],['a-demo-front','student-demo','j-frontend','Interview',-7],['a-demo-data','student-demo','j-data','Applied',-3],['a-diya-design','s2','j-design','Interview',-9],['a-ishaan-full','s3','j-fullstack','Applied',-4],['a-meera-design','s4','j-design','Shortlisted',-5],['a-arjun-full','s5','j-fullstack','Offered',-10],['a-sana-full','s6','j-fullstack','Selected',-11],['a-diya-full','s2','j-fullstack','Shortlisted',-5],['a-ishaan-design','s3','j-design','Rejected',-6],['a-sana-research','s6','j-research','Applied',-2],['a-arjun-product','s5','j-product','Interview',-9]];
const pipeline=['Applied','Shortlisted','Interview','Offered','Selected'];
for(const [id,student_id,job_id,status,start] of applications){const idx=pipeline.indexOf(status);const history=pipeline.slice(0,Math.max(1,idx+1)).map((stage,i)=>({status:stage,at:new Date(now.getTime()+(Number(start)+i)*86400000).toISOString(),by:i?'recruiter-demo':student_id,note:i?`You’ve moved to ${stage.toLowerCase()}. Keep your momentum.`:'Application received. Thanks for making your introduction.'}));if(status==='Rejected')history.push({status,at:new Date(now.getTime()-2*86400000).toISOString(),by:'recruiter-demo',note:'Thank you for your interest. We have moved forward with candidates whose work more closely fits this role.'});insert('applications',{id,student_id,job_id,status,snapshot:JSON.stringify(profiles[student_id]),history:JSON.stringify(history),created_at:at(Number(start))});}
insert('saved_jobs',{student_id:'student-demo',job_id:'j-product'});
for(const [i,target] of [...companies.filter(c=>c[7]==='approved').map(c=>({id:c[0],type:'company'})),...jobs.filter(j=>j[11]==='approved').map(j=>({id:j[0],type:'job'}))].entries())insert('audit_logs',{id:'log-seed-'+i,reviewer_id:'admin-demo',target_id:target.id,target_type:target.type,action:'approved',reason:target.type==='company'?'Company details reviewed and verified for this illustrative demo.':'Role, compensation, and eligibility criteria reviewed.',created_at:at(-15+i)});
mkdirSync('scripts',{recursive:true});writeFileSync('scripts/seed.sql','-- Illustrative demo data. Resume and company URLs are examples.\n'+sql.join('\n')+'\n');console.log(`Generated demo data: ${students.length} students, ${companies.length} companies, ${jobs.length} openings, ${applications.length} applications.`);
