-- Illustrative demo data. Resume and company URLs are examples.
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('student-demo','Aarav Sharma','student@campusbridge.demo','CSE',8.6,2027,'https://example.com/resumes/student-demo','Frontend enthusiast, curious problem solver, and builder of thoughtful digital experiences. I love React, design systems, and making complex things feel simple.','234cfb4fc46805bb779536ea715b6678df877002ec69a8aa716e3ba1c587a237','campusbridge-demo-student-demo','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('student-low','Rohan Mehta','ineligible@campusbridge.demo','CSE',6.4,2027,'https://example.com/resumes/student-low','Learning frontend development and building my first portfolio.','706a4d6e1a936c2e96a579faf2d23d877fe8c32c65a48eadd1f15db769c8406e','campusbridge-demo-student-low','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('s2','Diya Patel','diya@campusbridge.demo','IT',9.1,2027,'https://example.com/resumes/s2','Full-stack engineer with a love for accessible interfaces and open source.','1f1b3772311afa9b2d19eed69afb3e11ad16ec52cc865c6ff34567fd6e89d506','campusbridge-demo-s2','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('s3','Ishaan Rao','ishaan@campusbridge.demo','CSE',8.8,2027,'https://example.com/resumes/s3','Backend systems, distributed computing, and a healthy curiosity for how things work.','5322de189edebba52c2f067428504e055a395737e63bfe07d43cf7c9bf7da691','campusbridge-demo-s3','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('s4','Meera Iyer','meera@campusbridge.demo','ECE',8.3,2027,'https://example.com/resumes/s4','Product designer and electronics student interested in the intersection of people and technology.','b20ab2aa9a9a59736f60de7ff1171f56de5e6bd69dc24003108b64c7ec045efb','campusbridge-demo-s4','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('s5','Arjun Nair','arjun@campusbridge.demo','IT',8.9,2027,'https://example.com/resumes/s5','I build practical tools using TypeScript and Python.','acf34f8632a846a513bc383647093c932aa9a99a30985dd0888b306f9acba0b0','campusbridge-demo-s5','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('s6','Sana Khan','sana@campusbridge.demo','CSE',9.3,2027,'https://example.com/resumes/s6','Data science, machine learning, and asking better questions.','fcd41bec2fa6328bef11ec16093caa2d1599dc1a2526bdabc20e513d63e01356','campusbridge-demo-s6','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,department,cgpa,graduation_year,resume,bio,password,salt,role,created_at) VALUES ('s7','Dev Shah','dev@campusbridge.demo','ME',8.1,2027,'https://example.com/resumes/s7','Mechanical engineering student passionate about sustainable design.','465df93254a239f324fb9cf4f4dba653fa8606349bb5fa3398af964a3955b535','campusbridge-demo-s7','student','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,password,salt,role,created_at) VALUES ('recruiter-demo','Maya Kapoor','recruiter@campusbridge.demo','58a7428cfd4bda662fd195df164467cf3baad57c847d63ce87da4820518df588','campusbridge-demo-recruiter-demo','recruiter','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,password,salt,role,created_at) VALUES ('r2','Nikhil Verma','orbit@campusbridge.demo','98c56e1925a1f25bf623bd667782ff90eb33405f86d4c009364ddb1e883eb727','campusbridge-demo-r2','recruiter','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,password,salt,role,created_at) VALUES ('r3','Priya Desai','northstar@campusbridge.demo','a40ce4b274117841c3d989943ee88aed3f8ff3d07f9a3551850eaf5f1a5e7820','campusbridge-demo-r3','recruiter','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,password,salt,role,created_at) VALUES ('r4','Kavya Sen','monograph@campusbridge.demo','813a40a11eed2e0e7c70be372e57bf9650f21c10f5b5644ab1edd8f3518dfc70','campusbridge-demo-r4','recruiter','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,password,salt,role,created_at) VALUES ('r5','Rishi Arora','forma@campusbridge.demo','98e2aabdecd77a0fdae38db62ec535a88aa326e1261631746f0075f2b1f15c7c','campusbridge-demo-r5','recruiter','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,password,salt,role,created_at) VALUES ('r6','Ankit Roy','canopy@campusbridge.demo','c469287ffa9d9111c1336102fdc98e6c39a9d20c93f5c438507007dfbeceecaa','campusbridge-demo-r6','recruiter','2026-09-06 17:35:11');
INSERT OR IGNORE INTO users (id,name,email,password,salt,role,created_at) VALUES ('admin-demo','Ananya Rao','admin@campusbridge.demo','c1f06287eb14f148e24e1e7dde2b79ff35760048dd9a0400972a395a0c600aee','campusbridge-demo-admin-demo','admin','2026-09-06 17:35:11');
INSERT OR IGNORE INTO companies (id,owner_id,name,industry,location,logo,color,status,description,website,created_at) VALUES ('c-layers','recruiter-demo','Layers','Product & Design','Bengaluru','≋','#e9dff7','approved','We build thoughtful digital products for people and teams. Our small, ambitious studio values curiosity, craft, and a fresh perspective. Help us turn complex challenges into experiences people love.','https://example.com/companies/c-layers','2026-09-14 17:35:11');
INSERT OR IGNORE INTO companies (id,owner_id,name,industry,location,logo,color,status,description,website,created_at) VALUES ('c-orbit','r2','Orbit','Developer Tools','Bengaluru','◉','#dfeace','approved','We are building the tools that help developers do their best work. Join a collaborative engineering team that values clean code, good questions, and continuous learning.','https://example.com/companies/c-orbit','2026-09-14 17:35:11');
INSERT OR IGNORE INTO companies (id,owner_id,name,industry,location,logo,color,status,description,website,created_at) VALUES ('c-northstar','r3','Northstar','Technology & Data','Hyderabad','✦','#fae9c8','approved','We make data useful, accessible, and actionable. Our teams bring together analytical thinking and real-world impact to help businesses make better decisions.','https://example.com/companies/c-northstar','2026-09-14 17:35:11');
INSERT OR IGNORE INTO companies (id,owner_id,name,industry,location,logo,color,status,description,website,created_at) VALUES ('c-monograph','r4','Monograph','Software & Collaboration','Pune','m.','#e8e6df','approved','We make the workday a little clearer. Build calm, focused software for creative teams and grow with an engineering culture that values thoughtful collaboration.','https://example.com/companies/c-monograph','2026-09-14 17:35:11');
INSERT OR IGNORE INTO companies (id,owner_id,name,industry,location,logo,color,status,description,website,created_at) VALUES ('c-forma','r5','Forma','Engineering & Manufacturing','Mumbai','▰','#e6e4f3','pending','We are reimagining manufacturing with sustainable materials and precision engineering. We are looking for curious students to help shape the next generation of physical products.','https://example.com/companies/c-forma','2026-10-04 17:35:11');
INSERT OR IGNORE INTO companies (id,owner_id,name,industry,location,logo,color,status,description,website,created_at) VALUES ('c-canopy','r6','Canopy','Climate Technology','Chennai','♧','#dcebdc','pending','We help communities measure and reduce their environmental impact. Work with a growing climate technology team across data, design, and engineering.','https://example.com/companies/c-canopy','2026-10-04 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-design','c-layers','Product Design Intern','Internship','Bengaluru','Hybrid','₹35,000',7.5,'["CSE","IT","ECE"]','["Figma","Design thinking","Prototyping"]','2026-10-26','approved','We’re looking for a curious, motivated product design intern to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-09-30 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-frontend','c-orbit','Frontend Engineer','Full-time','Bengaluru','Hybrid','₹12–18 LPA',8,'["CSE","IT"]','["React","TypeScript","JavaScript"]','2026-10-31','approved','We’re looking for a curious, motivated frontend engineer to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-09-28 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-data','c-northstar','Data Analyst Intern','Internship','Hyderabad','On-site','₹30,000',7.5,'["CSE","IT","ECE"]','["SQL","Python","Data visualization"]','2026-10-24','approved','We’re looking for a curious, motivated data analyst intern to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-09-30 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-product','c-monograph','Associate Product Engineer','Full-time','Remote','Remote','₹10–14 LPA',8,'["CSE","IT"]','["Problem solving","React","Node.js"]','2026-11-05','approved','We’re looking for a curious, motivated associate product engineer to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-09-26 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-fullstack','c-layers','Full Stack Developer','Full-time','Bengaluru','Hybrid','₹14–20 LPA',8.5,'["CSE","IT"]','["TypeScript","Node.js","PostgreSQL"]','2026-10-28','approved','We’re looking for a curious, motivated full stack developer to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-09-29 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-research','c-northstar','Machine Learning Intern','Internship','Hyderabad','Hybrid','₹45,000',9,'["CSE","IT"]','["Python","Machine learning","Statistics"]','2026-11-03','approved','We’re looking for a curious, motivated machine learning intern to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-09-27 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-layers-new','c-layers','UI Engineering Intern','Internship','Bengaluru','Hybrid','₹40,000',7,'["CSE","IT"]','["CSS","React","Accessibility"]','2026-11-10','pending','We’re looking for a curious, motivated ui engineering intern to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-10-04 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-forma','c-forma','Graduate Design Engineer','Full-time','Mumbai','On-site','₹8–12 LPA',7,'["ME","EEE"]','["CAD","SolidWorks","Engineering design"]','2026-11-07','pending','We’re looking for a curious, motivated graduate design engineer to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-10-04 17:35:11');
INSERT OR IGNORE INTO jobs (id,company_id,title,type,location,mode,salary,min_cgpa,departments,skills,deadline,status,description,created_at) VALUES ('j-canopy','c-canopy','Software Engineering Intern','Internship','Chennai','Hybrid','₹25,000',7,'["CSE","IT","ECE"]','["JavaScript","Python","Git"]','2026-11-02','pending','We’re looking for a curious, motivated software engineering intern to join our team and help shape what’s next. You’ll work alongside experienced people who care about their craft and are excited to help you grow.
In this role, you’ll collaborate on real projects, turn ideas into thoughtful solutions, and learn through meaningful hands-on work. You’ll contribute from day one, with the support and mentorship to make your introduction count.
Bring your curiosity, a willingness to learn, and examples of work you’re proud of. We value clear communication, collaborative problem solving, and a fresh perspective. Our selection process includes a profile review, a practical conversation about your work, and a final team interview.','2026-10-04 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-demo-design','student-demo','j-design','Shortlisted','{"id":"student-demo","name":"Aarav Sharma","email":"student@campusbridge.demo","department":"CSE","cgpa":8.6,"graduation_year":2027,"resume":"https://example.com/resumes/student-demo","bio":"Frontend enthusiast, curious problem solver, and builder of thoughtful digital experiences. I love React, design systems, and making complex things feel simple."}','[{"status":"Applied","at":"2026-09-28T17:35:11.169Z","by":"student-demo","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-09-29T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."}]','2026-09-28 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-demo-front','student-demo','j-frontend','Interview','{"id":"student-demo","name":"Aarav Sharma","email":"student@campusbridge.demo","department":"CSE","cgpa":8.6,"graduation_year":2027,"resume":"https://example.com/resumes/student-demo","bio":"Frontend enthusiast, curious problem solver, and builder of thoughtful digital experiences. I love React, design systems, and making complex things feel simple."}','[{"status":"Applied","at":"2026-09-29T17:35:11.169Z","by":"student-demo","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-09-30T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."},{"status":"Interview","at":"2026-10-01T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to interview. Keep your momentum."}]','2026-09-29 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-demo-data','student-demo','j-data','Applied','{"id":"student-demo","name":"Aarav Sharma","email":"student@campusbridge.demo","department":"CSE","cgpa":8.6,"graduation_year":2027,"resume":"https://example.com/resumes/student-demo","bio":"Frontend enthusiast, curious problem solver, and builder of thoughtful digital experiences. I love React, design systems, and making complex things feel simple."}','[{"status":"Applied","at":"2026-10-03T17:35:11.169Z","by":"student-demo","note":"Application received. Thanks for making your introduction."}]','2026-10-03 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-diya-design','s2','j-design','Interview','{"id":"s2","name":"Diya Patel","email":"diya@campusbridge.demo","department":"IT","cgpa":9.1,"graduation_year":2027,"resume":"https://example.com/resumes/s2","bio":"Full-stack engineer with a love for accessible interfaces and open source."}','[{"status":"Applied","at":"2026-09-27T17:35:11.169Z","by":"s2","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-09-28T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."},{"status":"Interview","at":"2026-09-29T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to interview. Keep your momentum."}]','2026-09-27 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-ishaan-full','s3','j-fullstack','Applied','{"id":"s3","name":"Ishaan Rao","email":"ishaan@campusbridge.demo","department":"CSE","cgpa":8.8,"graduation_year":2027,"resume":"https://example.com/resumes/s3","bio":"Backend systems, distributed computing, and a healthy curiosity for how things work."}','[{"status":"Applied","at":"2026-10-02T17:35:11.169Z","by":"s3","note":"Application received. Thanks for making your introduction."}]','2026-10-02 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-meera-design','s4','j-design','Shortlisted','{"id":"s4","name":"Meera Iyer","email":"meera@campusbridge.demo","department":"ECE","cgpa":8.3,"graduation_year":2027,"resume":"https://example.com/resumes/s4","bio":"Product designer and electronics student interested in the intersection of people and technology."}','[{"status":"Applied","at":"2026-10-01T17:35:11.169Z","by":"s4","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-10-02T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."}]','2026-10-01 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-arjun-full','s5','j-fullstack','Offered','{"id":"s5","name":"Arjun Nair","email":"arjun@campusbridge.demo","department":"IT","cgpa":8.9,"graduation_year":2027,"resume":"https://example.com/resumes/s5","bio":"I build practical tools using TypeScript and Python."}','[{"status":"Applied","at":"2026-09-26T17:35:11.169Z","by":"s5","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-09-27T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."},{"status":"Interview","at":"2026-09-28T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to interview. Keep your momentum."},{"status":"Offered","at":"2026-09-29T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to offered. Keep your momentum."}]','2026-09-26 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-sana-full','s6','j-fullstack','Selected','{"id":"s6","name":"Sana Khan","email":"sana@campusbridge.demo","department":"CSE","cgpa":9.3,"graduation_year":2027,"resume":"https://example.com/resumes/s6","bio":"Data science, machine learning, and asking better questions."}','[{"status":"Applied","at":"2026-09-25T17:35:11.169Z","by":"s6","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-09-26T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."},{"status":"Interview","at":"2026-09-27T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to interview. Keep your momentum."},{"status":"Offered","at":"2026-09-28T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to offered. Keep your momentum."},{"status":"Selected","at":"2026-09-29T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to selected. Keep your momentum."}]','2026-09-25 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-diya-full','s2','j-fullstack','Shortlisted','{"id":"s2","name":"Diya Patel","email":"diya@campusbridge.demo","department":"IT","cgpa":9.1,"graduation_year":2027,"resume":"https://example.com/resumes/s2","bio":"Full-stack engineer with a love for accessible interfaces and open source."}','[{"status":"Applied","at":"2026-10-01T17:35:11.169Z","by":"s2","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-10-02T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."}]','2026-10-01 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-ishaan-design','s3','j-design','Rejected','{"id":"s3","name":"Ishaan Rao","email":"ishaan@campusbridge.demo","department":"CSE","cgpa":8.8,"graduation_year":2027,"resume":"https://example.com/resumes/s3","bio":"Backend systems, distributed computing, and a healthy curiosity for how things work."}','[{"status":"Applied","at":"2026-09-30T17:35:11.169Z","by":"s3","note":"Application received. Thanks for making your introduction."},{"status":"Rejected","at":"2026-10-04T17:35:11.169Z","by":"recruiter-demo","note":"Thank you for your interest. We have moved forward with candidates whose work more closely fits this role."}]','2026-09-30 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-sana-research','s6','j-research','Applied','{"id":"s6","name":"Sana Khan","email":"sana@campusbridge.demo","department":"CSE","cgpa":9.3,"graduation_year":2027,"resume":"https://example.com/resumes/s6","bio":"Data science, machine learning, and asking better questions."}','[{"status":"Applied","at":"2026-10-04T17:35:11.169Z","by":"s6","note":"Application received. Thanks for making your introduction."}]','2026-10-04 17:35:11');
INSERT OR IGNORE INTO applications (id,student_id,job_id,status,snapshot,history,created_at) VALUES ('a-arjun-product','s5','j-product','Interview','{"id":"s5","name":"Arjun Nair","email":"arjun@campusbridge.demo","department":"IT","cgpa":8.9,"graduation_year":2027,"resume":"https://example.com/resumes/s5","bio":"I build practical tools using TypeScript and Python."}','[{"status":"Applied","at":"2026-09-27T17:35:11.169Z","by":"s5","note":"Application received. Thanks for making your introduction."},{"status":"Shortlisted","at":"2026-09-28T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to shortlisted. Keep your momentum."},{"status":"Interview","at":"2026-09-29T17:35:11.169Z","by":"recruiter-demo","note":"You’ve moved to interview. Keep your momentum."}]','2026-09-27 17:35:11');
INSERT OR IGNORE INTO saved_jobs (student_id,job_id) VALUES ('student-demo','j-product');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-0','admin-demo','c-layers','company','approved','Company details reviewed and verified for this illustrative demo.','2026-09-21 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-1','admin-demo','c-orbit','company','approved','Company details reviewed and verified for this illustrative demo.','2026-09-22 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-2','admin-demo','c-northstar','company','approved','Company details reviewed and verified for this illustrative demo.','2026-09-23 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-3','admin-demo','c-monograph','company','approved','Company details reviewed and verified for this illustrative demo.','2026-09-24 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-4','admin-demo','j-design','job','approved','Role, compensation, and eligibility criteria reviewed.','2026-09-25 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-5','admin-demo','j-frontend','job','approved','Role, compensation, and eligibility criteria reviewed.','2026-09-26 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-6','admin-demo','j-data','job','approved','Role, compensation, and eligibility criteria reviewed.','2026-09-27 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-7','admin-demo','j-product','job','approved','Role, compensation, and eligibility criteria reviewed.','2026-09-28 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-8','admin-demo','j-fullstack','job','approved','Role, compensation, and eligibility criteria reviewed.','2026-09-29 17:35:11');
INSERT OR IGNORE INTO audit_logs (id,reviewer_id,target_id,target_type,action,reason,created_at) VALUES ('log-seed-9','admin-demo','j-research','job','approved','Role, compensation, and eligibility criteria reviewed.','2026-09-30 17:35:11');
