import React,{createContext,useContext,useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Check,Search,MapPin,Clock,Bookmark,Briefcase,GraduationCap,X,LoaderCircle} from 'lucide-react';
export type Role='student'|'recruiter'|'admin';
export type User={id:string;name:string;email:string;role:Role;department:string;cgpa:number;graduation_year:number;resume:string;bio:string};
export type Job={id:string;company_id:string;company_name:string;logo:string;color:string;title:string;type:string;location:string;mode:string;salary:string;min_cgpa:number;departments:string;deadline:string;description:string;skills:string;status:string;reason:string;created_at:string;company_status?:string};
export type Company={id:string;name:string;industry:string;website:string;location:string;description:string;logo:string;color:string;status:string;reason:string;owner_name?:string;owner_email?:string;created_at:string};
export type Application={id:string;student_id:string;student_name?:string;student_email?:string;job_id:string;title:string;company_name:string;logo:string;color:string;status:string;snapshot:string;history:string;created_at:string;salary:string;location:string};
export type State={user:User;companies:Company[];jobs:Job[];applications:Application[];students:User[];logs:any[];saved:string[]};
export const departments=['CSE','IT','ECE','EEE','ME','CE','MBA'];
export const stages=['Applied','Shortlisted','Interview','Offered','Selected'];
export const parse=(value:string,fallback:any[]=[])=>{try{return JSON.parse(value)}catch{return fallback}};
export const date=(value:string,opts?:Intl.DateTimeFormatOptions)=>new Date(value.includes('T')?value:value.replace(' ','T')+'Z').toLocaleDateString('en-IN',opts||{day:'numeric',month:'short',year:'numeric'});
export function go(path:string){window.history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'instant'});}
export async function api(path:string,method='GET',body?:any){const r=await fetch('/api'+path,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data;}
export const Context=createContext<{data:State;refresh:()=>Promise<void>;act:(path:string,method:string,body:any,message:string)=>Promise<boolean>;notify:(message:string,error?:boolean)=>void}>(null as any);
export const useApp=()=>useContext(Context);
export function ThemeToggle(){const [dark,setDark]=useState(document.documentElement.dataset.theme==='dark');return <button className="appearance-control" onClick={()=>{const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';localStorage.setItem('campusbridge-theme',next?'dark':'light')}} aria-label={'Switch to '+(dark?'light':'dark')+' appearance'}>{dark?'Light appearance':'Dark appearance'}<span className={'appearance-indicator '+(dark?'is-dark':'')}/></button>}
export function useModal(active=true){useEffect(()=>{if(!active)return;const previous=document.activeElement as HTMLElement;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=document.querySelector<HTMLElement>('[role="dialog"]');dialog?.querySelector<HTMLElement>('button,input,select,textarea,a[href]')?.focus();function keys(e:KeyboardEvent){if(e.key==='Escape'){dialog?.querySelector<HTMLButtonElement>('.modal-close')?.click();return}if(e.key==='Tab'&&dialog){const items=[...dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')].filter(el=>el.offsetParent!==null);if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||!dialog.contains(document.activeElement))){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!dialog.contains(document.activeElement))){e.preventDefault();first.focus()}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);document.body.style.overflow=previousOverflow;previous?.focus()}},[active]);}
export function Link({to,children,className='',...rest}:React.AnchorHTMLAttributes<HTMLAnchorElement>&{to:string}){return <a href={to} className={className} {...rest} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey)return;e.preventDefault();go(to)}}>{children}</a>}
export function Mark({small=false}:{small?:boolean}){return <span className={'brand '+(small?'small':'')}><span className="brand-symbol"><svg viewBox="0 0 28 28" fill="none"><path d="M5 21V11C5 5 23 5 23 11V21M5 15C5 9 23 9 23 15M9 21V12M19 21V12" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round"/></svg></span><span>campus<span className="brand-light">bridge</span><span className="brand-dot">.</span></span></span>}
export function Logo({name,logo,color,size=''}:{name:string;logo?:string;color?:string;size?:string}){return <div className={'company-logo '+size} style={{background:color||'#e6eadf'}} aria-label={name}>{logo||name[0]}</div>}
export function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase().replace(/\s/g,'-')}><span/>{value[0]?.toUpperCase()+value.slice(1)}</span>}
export function Button({children,busy=false,variant='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{busy?:boolean;variant?:string}){return <button {...props} disabled={busy||props.disabled} className={'btn '+variant+' '+(props.className||'')}>{busy?<LoaderCircle size={17} className="spin"/>:null}{children}</button>}
export function PageHead({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:React.ReactNode}){return <div className="page-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{children&&<div className="head-actions">{children}</div>}</div>}
export function Empty({title,description,children}:{title:string;description:string;children?:React.ReactNode}){return <div className="empty"><div className="empty-icon"><Briefcase size={25}/></div><h3>{title}</h3><p>{description}</p>{children}</div>}
export function Metric({label,value,detail,icon:Icon,accent=false}:{label:string;value:any;detail:string;icon:any;accent?:boolean}){return <div className={'metric '+(accent?'accent':'')}><div className="metric-top"><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><div className="metric-detail">{detail}</div></div>}
export function SearchBox({value,onChange,placeholder='Search opportunities…'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="searchbox"><Search size={18}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button aria-label="Clear search" onClick={()=>onChange('')}><X size={15}/></button>}</label>}
export function Eligibility({job,compact=false}:{job:Job;compact?:boolean}){const {data}=useApp();const u=data.user;const ok=Number(u.cgpa)>=job.min_cgpa&&parse(job.departments).includes(u.department)&&!!u.resume;return <span className={'eligibility '+(ok?'yes':'no')}>{ok?<Check size={13}/>:<GraduationCap size={13}/>} {ok?'You’re eligible':compact?'Check eligibility':'Review eligibility'}</span>}
export function JobCard({job}:{job:Job}){const {data,act}=useApp();const saved=data.saved.includes(job.id);return <article className="job-card"><div className="job-card-top"><Logo name={job.company_name} logo={job.logo} color={job.color}/><button className={'icon-button bookmark '+(saved?'is-saved':'')} aria-label={saved?'Unsave opening':'Save opening'} onClick={()=>void act('/saved/'+job.id,saved?'DELETE':'POST',undefined,saved?'Opening removed from saved':'Opening saved')}><Bookmark size={19} fill={saved?'currentColor':'none'}/></button></div><div className="company-name">{job.company_name} <span className="verified">✓</span></div><Link to={'/student/opportunities/'+job.id}><h3>{job.title}</h3></Link><div className="job-meta"><span><MapPin size={13}/>{job.location}</span><span>{job.mode}</span></div><div className="tags"><span>{job.type}</span><span>{job.min_cgpa}+ CGPA</span><span>{parse(job.departments).slice(0,2).join(' · ')}</span></div><div className="job-card-bottom"><strong>{job.salary}<small>{job.type==='Internship'?'/ month':'/ year'}</small></strong><Link to={'/student/opportunities/'+job.id} className="round-link" aria-label={'View '+job.title}><ArrowUpRight size={20}/></Link></div><div className="job-foot"><Eligibility job={job} compact/><span><Clock size={12}/> {date(job.deadline,{day:'numeric',month:'short'})}</span></div></article>}
export function Timeline({application}:{application:Application}){const history=parse(application.history);const current=stages.indexOf(application.status);return <div className="timeline">{stages.map((s,i)=>{const entry=history.find((h:any)=>h.status===s);return <div className={'timeline-step '+(i<=current?'completed':'')+' '+(i===current?'current':'')} key={s}><div className="timeline-dot">{i<current?<Check size={15}/>:i+1}</div><div><h4>{s}</h4><p>{entry?date(entry.at):i===current+1?'Next step':'Awaiting previous stage'}</p>{entry?.note&&<small>{entry.note}</small>}</div></div>})}{application.status==='Rejected'&&<div className="timeline-step rejected"><div className="timeline-dot"><X size={15}/></div><div><h4>Rejected</h4><p>{date(history[history.length-1].at)}</p><small>{history[history.length-1].note}</small></div></div>}</div>}
